### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by nbao** [fivefilters/readability.php#28] opened 2024-02-06 00:20 UTC
if i use 
composer require fivefilters/readability.php **it download only version 1**
if i run 
**composer require fivefilters/readability.php:^3**
I got error
Problem 1
    - fivefilters/readability.php[v3.1.5, ..., v3.1.6] require league/uri ~6.7.2 -> satisfiable by league/uri[6.7.2].
    - fivefilters/readability.php[v3.0.0, ..., v3.1.4] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - league/uri 6.7.2 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires fivefilters/readability.php ^3 -> satisfiable by fivefilters/readability.php[v3.0.0, ..., v3.1.6].

**Comment by fivefilters** [comment] 2024-04-19 13:46
Hi there, sorry for the late reply to this. I haven't been able to reproduce this. I suspect the error you're seeing is due to different versions of the packages you have installed already for your project. I will close this, but if you do think it's an issue with this repo, please provide some steps to reproduce the problem.

```
> composer require fivefilters/readability.php
Using version ^3.1 for fivefilters/readability.php
./composer.json has been created
Running composer update fivefilters/readability.php
Loading composer repositories with package information
Updating dependencies
Lock file operations: 6 installs, 0 updates, 0 removals
  - Locking fivefilters/readability.php (v3.1.6)
  - Locking league/uri (6.7.2)
  - Locking league/uri-interfaces (2.3.0)
  - Locking masterminds/html5 (2.9.0)
  - Locking psr/http-message (1.1)
  - Locking psr/log (3.0.0)
```

**Comment by fivefilters** [comment] 2024-04-20 10:52
Was able to reproduce this now on another project. I think we need to update the versions in the composer file. Otherwise those libraries will need to be downgraded to be compatible.

**Comment by fivefilters** [comment] 2024-04-21 13:39
Version 3.2.0 - https://github.com/fivefilters/readability.php/releases/tag/v3.2.0 - now relies on newer versions of the dependencies, so hopefully you will less likely to encounter issues like this when installing Readability in existing applications.

**Closed by fivefilters** 2024-04-21 13:39 UTC
